# 数据库链接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  main:
    allow-circular-references: true
  thymeleaf:
    cache: true

# mybatis配置
mybatis:
  type-aliases-package: com.zzp.pojo
  mapper-locations: classpath*:mybatis/*.xml

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8082

# mica-xss配置
mica:
  xss:
    enabled: true
    path-patterns:
      - /comments
      - /messageboardcommentinsert

#日志配置
logging:
  lever:
    root: info
    com.heshijia: debug
  #配置日志文件存放路径
  file:
    path: log/blog/